webtalk_init -webtalk_dir C:/Users/panta/OneDrive - Politecnico di Milano/Documenti/Progetto di Reti Logiche/project_basicstuff/project_basicstuff.sim/sim_1/behav/xsim/xsim.dir/T01_HelloWorldTB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar  3 18:33:12 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ab0c514d-6441-4773-9ef7-df48c27c0165" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ea2ec178ada042c4be7670dc3dcc9730" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6272_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1838241374 -regid "" -xml C:/Users/panta/OneDrive - Politecnico di Milano/Documenti/Progetto di Reti Logiche/project_basicstuff/project_basicstuff.sim/sim_1/behav/xsim/xsim.dir/T01_HelloWorldTB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/panta/OneDrive - Politecnico di Milano/Documenti/Progetto di Reti Logiche/project_basicstuff/project_basicstuff.sim/sim_1/behav/xsim/xsim.dir/T01_HelloWorldTB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/panta/OneDrive - Politecnico di Milano/Documenti/Progetto di Reti Logiche/project_basicstuff/project_basicstuff.sim/sim_1/behav/xsim/xsim.dir/T01_HelloWorldTB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
